/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.UserController;
import javax.swing.JOptionPane;
import model.UserModel;
/**
 *
 * @author user
 */
public class RegistrationScreen extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationScreen
     */
    public RegistrationScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        lName = new javax.swing.JTextField();
        uEmail = new javax.swing.JTextField();
        uNid = new javax.swing.JTextField();
        cPassword = new javax.swing.JPasswordField();
        uPassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 500));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setText("Registration");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 30, 210, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 140, 90, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setText("UserName");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 180, 90, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setText("National Id");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 220, 90, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 260, 90, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Already have an account?");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 410, 160, 20);

        fName.setBackground(new java.awt.Color(91, 146, 198));
        getContentPane().add(fName);
        fName.setBounds(380, 90, 210, 30);

        lName.setBackground(new java.awt.Color(91, 146, 198));
        getContentPane().add(lName);
        lName.setBounds(380, 130, 210, 30);

        uEmail.setBackground(new java.awt.Color(91, 146, 198));
        getContentPane().add(uEmail);
        uEmail.setBounds(380, 170, 210, 30);

        uNid.setBackground(new java.awt.Color(91, 146, 198));
        getContentPane().add(uNid);
        uNid.setBounds(380, 210, 210, 30);

        cPassword.setBackground(new java.awt.Color(91, 146, 198));
        getContentPane().add(cPassword);
        cPassword.setBounds(380, 290, 210, 30);

        uPassword.setBackground(new java.awt.Color(91, 146, 198));
        getContentPane().add(uPassword);
        uPassword.setBounds(380, 250, 210, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setText("First Name");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 90, 90, 40);

        jButton1.setBackground(new java.awt.Color(59, 234, 234));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 350, 200, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel9.setText("Confirm Password");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(250, 300, 120, 20);

        jLabel1.setForeground(new java.awt.Color(0, 255, 153));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 410, 50, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Frame 4fj.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 800, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String firstName = fName.getText();
        String lastName = lName.getText();
        String email = uEmail.getText();
        String dob = uNid.getText();
        String passwordd = uPassword.getText();
        String confirmPass = cPassword.getText();
        
        if (firstName.equals("")|| lastName.equals("")|| email.equals("")|| dob.equals("")){
            JOptionPane.showMessageDialog(this,"empty field not accepted!!", "error",JOptionPane.ERROR_MESSAGE);
                  
        }
        else{
        if(passwordd.equals(confirmPass)){
            UserModel user= new UserModel(firstName,lastName,email,dob,passwordd);
            UserController uc= new UserController();
            uc.insertUser(user); 
            int result = JOptionPane.showConfirmDialog(null, "Registration sucessfull, Would you like to Login?", "Confirmation", JOptionPane.OK_OPTION);

            if (result == JOptionPane.OK_OPTION) {
                
                this.dispose();
            }

        }
        else{
            JOptionPane.showMessageDialog(this,"password and confirm passoword do not match!!", "error",JOptionPane.ERROR_MESSAGE);
            
            
        }
        
        
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cPassword;
    private javax.swing.JTextField fName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lName;
    private javax.swing.JTextField uEmail;
    private javax.swing.JTextField uNid;
    private javax.swing.JPasswordField uPassword;
    // End of variables declaration//GEN-END:variables
}
